#  Copyright 2019 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebs-nodes
  labels: 
    role: ebs
spec:
  selector:
    matchLabels:
      role: ebs
  template:
    metadata:
      labels:
        role: ebs
    spec:
      nodeSelector:
        role: ebs
      hostNetwork: true
      containers:
        - name: ebs-container
          image: jwkaguya/anna
          env: 
          - name: SERVER_TYPE
            value: "ebs"
          - name: ROUTING_IPS
            value: ROUTING_IPS_DUMMY
          - name: SEED_IP
            value: SEED_IP_DUMMY
          - name: MGMT_IP
            value: MGMT_IP_DUMMY
          - name: MON_IPS
            value: MON_IPS_DUMMY
          - name: REPO_ORG
            value: satorikoishi
          - name: REPO_BRANCH
            value: master
          - name: IFACE
            value: eno1
          volumeMounts:
          - mountPath: /ebs/ebs_0
            name: ebs0
          - mountPath: /ebs/ebs_1
            name: ebs1
          - mountPath: /ebs/ebs_2
            name: ebs2
          - mountPath: /ebs/ebs_3
            name: ebs3
      volumes:
      - name: ebs0
        hostPath:
          path: /ebs/ebs_0
          type: Directory
      - name: ebs1
        hostPath:
          path: /ebs/ebs_1
          type: Directory
      - name: ebs2
        hostPath:
          path: /ebs/ebs_2
          type: Directory
      - name: ebs3
        hostPath:
          path: /ebs/ebs_3
          type: Directory
